interface IEventTestingDataProps {}

const EventTestingData = [
  {
    url: '/dewa19.jpg',
    date: '5 Aug 2024',
    title: 'GOPHORIA - Dewa19 Gorontalo',
    price: 'Rp. 677.000,-',
    username: 'Deal Indonesia',
    location: 'Jakarta',
    category: 'music',
  },

  {
    url: '/LiSa2.webp',
    date: '28 Dec 2024',
    title: 'Live is Smile Always',
    price: 'Rp. 830.000,-',
    username: 'FLASHBACK motion',
    location: 'Bandung',
    category: 'music',
  },
  {
    url: '/anggun.png',
    date: '28 Jul 2024',
    title: 'Enchanting Anggun & Friends',
    price: 'Rp. 677.000,-',
    username: 'FLASHBACK motion',
    location: 'Surabaya',
    category: 'music',
  },
  {
    url: '/gedebagejazz.jpg',
    date: '1 Jun 2024',
    title: 'Enchanting Anggun & Friends',
    price: 'Rp. 350.000,-',
    username: 'Summarecon Mall Bandung',
    location: 'Bandung',
    category: 'music',
  },

  {
    url: '/gedebagejazz.jpg',
    date: '11 May 2024',
    title: 'Gedebage Jazz Festival',
    price: 'Rp. 239.000,-',
    username: 'Summarecon Mall Bandung',
    location: 'Bandung',
    category: 'music',
  },
  {
    url: '/ultrabeach.jpg',
    date: '7 Jun 2024',
    title: 'Ultra Beach Bali 2024',
    price: 'Rp. 2.100.000,-',
    username: 'Ultra Beach Bali',
    location: 'Bali',
    category: 'music',
  },
  {
    url: 'anggun.png',
    date: '28 Jul 2024',
    title: 'Enchanting Anggun & Friends',
    price: 'Rp. 677.000,-',
    username: 'FLASHBACK motion',
    location: 'Surabaya',
    category: 'music',
  },
  {
    url: '/dewa19.jpg',
    date: '5 Aug 2024',
    title: 'GOPHORIA - Dewa19 Gorontalo',
    price: 'Rp. 677.000,-',
    username: 'Deal Indonesia',
    location: 'Tangerang',
    category: 'music',
  },
  {
    url: '/nelangsa.jpg',
    date: '05 May 2024',
    title: 'Sajian Spesial Bilal Indrajaya: Konser Nelangsa Kala Purnama',
    price: 'Rp. 450.000,-',
    username: 'Aksara Records',
    location: 'Surabaya',
    category: 'festival',
  },
  {
    url: '/funrun.jpg',
    date: '12 May 2024',
    title: 'ESQ Fun Charity Run',
    price: 'Rp. 200.000,-',
    username: 'UAG University',
    location: 'Tangerang',
    category: 'festival',
  },
  {
    url: '/alcorfest.jpg',
    date: '01 Aug 2024',
    title: 'Alcor Fest 2024',
    price: 'Rp. 600.000,-',
    username: 'Goodworks',
    location: 'Jakarta',
    category: 'festival',
  },
  {
    url: '/batakfestival.jpg',
    date: '24 May 2024',
    title: 'BATAK FESTIVAL',
    price: 'Rp. 90.000,-',
    username: 'Samarga House',
    location: 'Tangerang',
    category: 'festival',
  },
  {
    url: '/momandbabyexpo.jpg',
    date: '3 May 2024',
    title: 'Indonesia Mom and Baby Expo IMOBY Surabaya 2024',
    price: 'Rp. 20.000,-',
    username: 'PT. MYExpo Kreasi Indonesia',
    location: 'Jakarta',
    category: 'festival',
  },
  {
    url: '/nebsfestival.jpg',
    date: '1 Jun 2024',
    title: 'NEBS Festival',
    price: 'Rp. 100.000,-',
    username: 'PERMUDHITA',
    location: 'Jakarta',
    category: 'festival',
  },
  {
    url: '/batakfestival.jpg',
    date: '24 May 2024',
    title: 'BATAK FESTIVAL',
    price: 'Rp. 90.000,-',
    username: 'Samarga House',
    category: 'festival',
  },
  {
    url: '/alcorfest.jpg',
    date: '01 Aug 2024',
    title: 'Alcor Fest 2024',
    price: 'Rp. 600.000,-',
    username: 'Goodworks',
    location: 'Jakarta',
    category: 'festival',
  },
  {
    url: '/momandbabyexpo.jpg',
    date: '3 May 2024',
    title: 'Indonesia Mom and Baby Expo IMOBY Surabaya 2024',
    price: 'Rp. 20.000,-',
    username: 'PT. MYExpo Kreasi Indonesia',
    location: 'Jakarta',
    category: 'festival',
  },
];

export default EventTestingData;
